import type { LocalModelCatalogEntry } from "@verdicta/shared";

type CuratedModel = Omit<LocalModelCatalogEntry, "downloads" | "likes" | "updatedAt" | "files" | "modalities" | "languages"> & {
  downloads?: number;
  likes?: number;
  updatedAt?: string | null;
  modalities?: string[];
  languages?: string[];
};

const curated = (entry: CuratedModel): CuratedModel => ({
  downloads: 0,
  likes: 0,
  updatedAt: null,
  modalities: ["Text"],
  collections: [],
  strengths: [],
  limitations: [],
  languages: ["English"],
  benchmarkArenaElo: null,
  benchmarkMmlu: null,
  benchmarkGsm8k: null,
  benchmarkHumanEval: null,
  benchmarkTokensPerSecond: null,
  ...entry
});

export const curatedModels: CuratedModel[] = [
  curated({
    repoId: "bartowski/Llama-3.1-8B-Instruct-GGUF",
    name: "Llama 3.1 8B Instruct",
    author: "bartowski",
    publisher: "Meta",
    family: "Llama",
    architecture: "Llama 3.1",
    summary: "Balanced general-purpose local assistant with broad ecosystem support and reliable instruction following.",
    tags: ["chat", "instruct", "general", "writing"],
    capabilities: ["Chat", "Writing", "Reasoning", "Summarization"],
    useCases: ["General assistant", "Legal drafting support", "Document Q&A", "Everyday local chat"],
    collections: ["Best for your machine", "Best for most users", "General purpose"],
    featuredCategory: "Best for most users",
    parameterLabel: "8B",
    parameterCountBillions: 8,
    contextWindowTokens: 128000,
    license: "Llama 3.1 Community",
    homepage: "https://huggingface.co/bartowski/Llama-3.1-8B-Instruct-GGUF",
    releaseDate: "2024-07-23",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "A safe default when you want good chat quality without stepping into 12B to 14B memory demands.",
    fitNotes: "Runs well on mainstream 16 GB RAM systems and benefits from mid-range GPUs.",
    strengths: ["Good instruction following", "Strong ecosystem support", "Stable default for mixed workloads"],
    limitations: ["Not specialized for code", "Reasoning trails smaller than larger distilled reasoning models"],
    languages: ["English", "Spanish", "Portuguese", "French"],
    benchmarkNote: "Editorial pick for balanced quality-per-GB rather than a single benchmark win.",
    benchmarkArenaElo: 1180,
    benchmarkMmlu: 66.7,
    benchmarkGsm8k: 76.0,
    benchmarkTokensPerSecond: 42,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Llama-3.2-3B-Instruct-GGUF",
    name: "Llama 3.2 3B Instruct",
    author: "bartowski",
    publisher: "Meta",
    family: "Llama",
    architecture: "Llama 3.2",
    summary: "Compact assistant for older laptops and low-memory desktops where speed matters more than peak quality.",
    tags: ["chat", "fast", "small"],
    capabilities: ["Chat", "Writing", "Fast inference"],
    useCases: ["Older hardware", "Quick local chat", "Offline notes"],
    collections: ["Best for your machine", "Small and fast"],
    featuredCategory: "Small and fast",
    parameterLabel: "3B",
    parameterCountBillions: 3,
    contextWindowTokens: 128000,
    license: "Llama 3.2 Community",
    homepage: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF",
    releaseDate: "2024-09-25",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Ideal when you need a lightweight local model that still feels modern and responsive.",
    fitNotes: "Good entry point for 8 GB RAM systems and integrated graphics machines.",
    strengths: ["Very easy to run", "Responsive inference", "Good fallback default"],
    limitations: ["Lower reasoning depth", "Limited coding quality versus 7B and 14B models"],
    benchmarkTokensPerSecond: 72,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    minimumVramGb: 4,
    recommendedVramGb: 6
  }),
  curated({
    repoId: "bartowski/Qwen2.5-7B-Instruct-GGUF",
    name: "Qwen2.5 7B Instruct",
    author: "bartowski",
    publisher: "Qwen",
    family: "Qwen",
    architecture: "Qwen2.5",
    summary: "Compact high-quality instruct model with unusually strong reasoning and multilingual utility for its size.",
    tags: ["chat", "reasoning", "multilingual", "instruct"],
    capabilities: ["Chat", "Reasoning", "Multilingual", "Writing"],
    useCases: ["Research chat", "Drafting", "Multilingual work", "Structured responses"],
    collections: ["Best for your machine", "Best for most users", "Multilingual"],
    featuredCategory: "Best for most users",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 131072,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-GGUF",
    releaseDate: "2024-09-19",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "One of the strongest quality-per-GB picks for mixed reasoning and writing.",
    fitNotes: "Especially attractive for machines with 16 GB RAM and optional mid-range GPU offload.",
    strengths: ["Strong multilingual support", "Great value at 7B", "Long-context capable"],
    limitations: ["Coding is good but not best-in-class", "Can slow down at very large contexts on CPU"],
    languages: ["English", "Spanish", "Portuguese", "French", "German", "Chinese"],
    benchmarkArenaElo: 1205,
    benchmarkMmlu: 70.0,
    benchmarkGsm8k: 83.0,
    benchmarkTokensPerSecond: 39,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Qwen2.5-14B-Instruct-GGUF",
    name: "Qwen2.5 14B Instruct",
    author: "bartowski",
    publisher: "Qwen",
    family: "Qwen",
    architecture: "Qwen2.5",
    summary: "Higher-quality general instruct model for users who want stronger reasoning and writing than 7B class models.",
    tags: ["chat", "reasoning", "multilingual", "long-context"],
    capabilities: ["Chat", "Reasoning", "Multilingual", "Long context"],
    useCases: ["Primary desktop assistant", "Large document analysis", "Higher-quality drafting"],
    collections: ["Power users", "Best long-context models", "Multilingual"],
    featuredCategory: "Power users",
    parameterLabel: "14B",
    parameterCountBillions: 14,
    contextWindowTokens: 131072,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF",
    releaseDate: "2024-09-19",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Worth the extra memory when you want a clear step up in overall quality from 7B defaults.",
    fitNotes: "Best on 24 GB RAM or higher, with clear gains from 10 GB+ VRAM for smoother offload.",
    strengths: ["Strong overall quality", "Very good multilingual support", "Handles long context well"],
    limitations: ["Heavier startup and lower tok/s", "Less attractive for older hardware"],
    languages: ["English", "Spanish", "Portuguese", "French", "German", "Chinese"],
    benchmarkArenaElo: 1245,
    benchmarkMmlu: 76.0,
    benchmarkGsm8k: 88.0,
    benchmarkTokensPerSecond: 24,
    minimumRamGb: 14,
    recommendedRamGb: 24,
    minimumVramGb: 10,
    recommendedVramGb: 12
  }),
  curated({
    repoId: "bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
    name: "Qwen2.5 Coder 7B",
    author: "bartowski",
    publisher: "Qwen",
    family: "Qwen Coder",
    architecture: "Qwen2.5",
    summary: "Developer-focused local model for code generation, debugging, explanation, and terminal assistance.",
    tags: ["code", "chat", "instruct", "reasoning"],
    capabilities: ["Coding", "Chat", "Reasoning"],
    useCases: ["Code generation", "Debugging", "Refactoring", "Shell help"],
    collections: ["Best coding models", "Best for your machine"],
    featuredCategory: "Best coding models",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 131072,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
    releaseDate: "2024-11-13",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "The best coding-first balance if you want strong repo help on mid-range hardware.",
    fitNotes: "Good all-round coding pick for 16 GB RAM desktops.",
    strengths: ["Great code completion quality", "Long context", "Useful for debugging and explanation"],
    limitations: ["Not multimodal", "General writing is secondary to code tasks"],
    benchmarkHumanEval: 78.0,
    benchmarkTokensPerSecond: 37,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Qwen2.5-Coder-14B-Instruct-GGUF",
    name: "Qwen2.5 Coder 14B",
    author: "bartowski",
    publisher: "Qwen",
    family: "Qwen Coder",
    architecture: "Qwen2.5",
    summary: "Higher-end coding model for serious local development workflows and larger repositories.",
    tags: ["code", "reasoning", "long-context"],
    capabilities: ["Coding", "Reasoning", "Long context"],
    useCases: ["Primary coding assistant", "Larger repos", "Refactors", "Architecture Q&A"],
    collections: ["Best coding models", "Power users"],
    featuredCategory: "Best coding models",
    parameterLabel: "14B",
    parameterCountBillions: 14,
    contextWindowTokens: 131072,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Qwen2.5-Coder-14B-Instruct-GGUF",
    releaseDate: "2024-11-13",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Choose this when coding quality matters more than latency and your machine can carry it.",
    fitNotes: "Best for workstations with 24 GB RAM and stronger GPU offload.",
    strengths: ["Best coding quality in this built-in catalog tier", "Long context", "Good repo reasoning"],
    limitations: ["Heavier than 7B models", "Lower tokens-per-second on CPU"],
    benchmarkHumanEval: 86.0,
    benchmarkTokensPerSecond: 22,
    minimumRamGb: 14,
    recommendedRamGb: 24,
    minimumVramGb: 10,
    recommendedVramGb: 12
  }),
  curated({
    repoId: "bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF",
    name: "DeepSeek R1 Distill Qwen 7B",
    author: "bartowski",
    publisher: "DeepSeek",
    family: "DeepSeek",
    architecture: "Qwen distill",
    summary: "Reasoning-oriented distilled model for more deliberate step-by-step analysis at 7B scale.",
    tags: ["reasoning", "analysis", "math"],
    capabilities: ["Reasoning", "Analysis", "Math"],
    useCases: ["Step-by-step analysis", "Logic-heavy prompts", "Reasoning workflows"],
    collections: ["Reasoning picks", "Best for your machine"],
    featuredCategory: "Reasoning picks",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 32768,
    license: "MIT / Apache-compatible",
    homepage: "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF",
    releaseDate: "2025-01-20",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Use this when deliberate reasoning quality matters more than the fastest chat experience.",
    fitNotes: "Still practical on 16 GB RAM machines despite its reasoning bias.",
    strengths: ["Strong chain-of-thought style behavior", "Useful for analysis and math-heavy prompts"],
    limitations: ["Can be slower and more verbose", "Less ideal as a fast everyday chat default"],
    benchmarkGsm8k: 89.0,
    benchmarkTokensPerSecond: 29,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF",
    name: "DeepSeek R1 Distill Llama 8B",
    author: "bartowski",
    publisher: "DeepSeek",
    family: "DeepSeek",
    architecture: "Llama distill",
    summary: "Reasoning-focused distilled model on a Llama base, useful if you prefer the Llama ecosystem.",
    tags: ["reasoning", "analysis", "chat"],
    capabilities: ["Reasoning", "Analysis", "Chat"],
    useCases: ["Structured reasoning", "Math", "Deliberate answers"],
    collections: ["Reasoning picks"],
    featuredCategory: "Reasoning picks",
    parameterLabel: "8B",
    parameterCountBillions: 8,
    contextWindowTokens: 32768,
    license: "Custom / research friendly",
    homepage: "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF",
    releaseDate: "2025-01-20",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Good alternative reasoning pick if you prefer Llama-family behavior and tooling familiarity.",
    strengths: ["Good analysis quality", "Familiar Llama-family feel"],
    limitations: ["Lower throughput", "Not the best choice for casual chat"],
    benchmarkGsm8k: 87.0,
    benchmarkTokensPerSecond: 27,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/gemma-2-9b-it-GGUF",
    name: "Gemma 2 9B IT",
    author: "bartowski",
    publisher: "Google",
    family: "Gemma",
    architecture: "Gemma 2",
    summary: "Fast, quality-focused instruction model with strong response quality for its weight class.",
    tags: ["chat", "instruct", "reasoning"],
    capabilities: ["Chat", "Reasoning", "Writing"],
    useCases: ["General assistant", "Drafting", "Fast iteration"],
    collections: ["Fast on consumer GPUs", "General purpose"],
    featuredCategory: "Fast on consumer GPUs",
    parameterLabel: "9B",
    parameterCountBillions: 9,
    contextWindowTokens: 8192,
    license: "Gemma",
    homepage: "https://huggingface.co/bartowski/gemma-2-9b-it-GGUF",
    releaseDate: "2024-06-27",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Good when you want stronger quality than 7B without fully jumping into 14B-class costs.",
    strengths: ["Strong instruction tuning", "Good quality on mid-range GPUs"],
    limitations: ["Shorter context than leading long-context picks"],
    benchmarkArenaElo: 1210,
    benchmarkTokensPerSecond: 33,
    minimumRamGb: 10,
    recommendedRamGb: 18,
    minimumVramGb: 8,
    recommendedVramGb: 10
  }),
  curated({
    repoId: "bartowski/gemma-3-12b-it-GGUF",
    name: "Gemma 3 12B IT",
    author: "bartowski",
    publisher: "Google",
    family: "Gemma",
    architecture: "Gemma 3",
    summary: "Newer Gemma-family step up for users who want stronger quality and broader capabilities on capable desktops.",
    tags: ["chat", "reasoning", "general"],
    capabilities: ["Chat", "Reasoning", "Writing"],
    useCases: ["Primary desktop assistant", "Research", "Higher-quality drafting"],
    collections: ["Power users", "General purpose"],
    featuredCategory: "Power users",
    parameterLabel: "12B",
    parameterCountBillions: 12,
    contextWindowTokens: 32768,
    license: "Gemma",
    homepage: "https://huggingface.co/bartowski/gemma-3-12b-it-GGUF",
    releaseDate: "2025-03-12",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "A good step up when you want more quality but still need a manageable desktop model.",
    strengths: ["Improved answer quality", "Good everyday balance for stronger hardware"],
    limitations: ["Heavier than 7B defaults", "Less proven catalog breadth than older staples"],
    benchmarkArenaElo: 1230,
    benchmarkMmlu: 75.0,
    benchmarkTokensPerSecond: 26,
    minimumRamGb: 12,
    recommendedRamGb: 22,
    minimumVramGb: 8,
    recommendedVramGb: 12
  }),
  curated({
    repoId: "bartowski/Mistral-Nemo-Instruct-2407-GGUF",
    name: "Mistral Nemo Instruct",
    author: "bartowski",
    publisher: "Mistral AI",
    family: "Mistral",
    architecture: "Mistral Nemo",
    summary: "Longer-context general assistant with solid instruction following and good desktop speed.",
    tags: ["chat", "long-context", "instruct"],
    capabilities: ["Chat", "Reasoning", "Long context"],
    useCases: ["Large document review", "Long transcripts", "Extended drafting sessions"],
    collections: ["Best long-context models", "General purpose"],
    featuredCategory: "Best long-context models",
    parameterLabel: "12B",
    parameterCountBillions: 12,
    contextWindowTokens: 128000,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF",
    releaseDate: "2024-07-18",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Recommended when you need more context headroom than smaller 7B-class models provide.",
    strengths: ["Strong long-context utility", "Good drafting flow", "Solid desktop speed"],
    limitations: ["Not the strongest coding pick", "12B-class resource demand"],
    benchmarkTokensPerSecond: 25,
    minimumRamGb: 12,
    recommendedRamGb: 24,
    minimumVramGb: 8,
    recommendedVramGb: 12
  }),
  curated({
    repoId: "bartowski/Mistral-Small-24B-Instruct-2501-GGUF",
    name: "Mistral Small 24B Instruct",
    author: "bartowski",
    publisher: "Mistral AI",
    family: "Mistral",
    architecture: "Mistral Small",
    summary: "Large local instruct model for higher-end desktops that want a major quality jump without cloud usage.",
    tags: ["chat", "reasoning", "power-user"],
    capabilities: ["Chat", "Reasoning", "Writing", "Long context"],
    useCases: ["High-end local assistant", "Better long-form drafting", "More complex reasoning"],
    collections: ["Power users"],
    featuredCategory: "Power users",
    parameterLabel: "24B",
    parameterCountBillions: 24,
    contextWindowTokens: 32768,
    license: "Mistral Research",
    homepage: "https://huggingface.co/bartowski/Mistral-Small-24B-Instruct-2501-GGUF",
    releaseDate: "2025-01-30",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Use on stronger workstations when you want a visible quality increase over 7B to 14B defaults.",
    fitNotes: "Expect 32 GB RAM class machines and meaningful GPU offload for a comfortable experience.",
    strengths: ["Higher-quality outputs", "Better depth on harder prompts"],
    limitations: ["Heavy", "Not a mass-market default"],
    benchmarkArenaElo: 1275,
    benchmarkTokensPerSecond: 14,
    minimumRamGb: 24,
    recommendedRamGb: 32,
    minimumVramGb: 14,
    recommendedVramGb: 16
  }),
  curated({
    repoId: "bartowski/Phi-3.5-mini-instruct-GGUF",
    name: "Phi 3.5 Mini Instruct",
    author: "bartowski",
    publisher: "Microsoft",
    family: "Phi",
    architecture: "Phi 3.5",
    summary: "Small, efficient model for low-memory systems and responsive local chat.",
    tags: ["chat", "small", "fast"],
    capabilities: ["Chat", "Writing", "Fast inference"],
    useCases: ["Low-memory machines", "Fast iteration", "Portable local AI"],
    collections: ["Small and fast", "Best for your machine"],
    featuredCategory: "Small and fast",
    parameterLabel: "3.8B",
    parameterCountBillions: 3.8,
    contextWindowTokens: 128000,
    license: "MIT",
    homepage: "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF",
    releaseDate: "2024-08-20",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Best starting point for older hardware or when latency matters more than maximum quality.",
    strengths: ["Very fast", "Easy to run", "Good compact utility model"],
    limitations: ["Less capable than modern 7B picks", "Not ideal for harder reasoning"],
    benchmarkTokensPerSecond: 68,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    minimumVramGb: 4,
    recommendedVramGb: 6
  }),
  curated({
    repoId: "bartowski/Phi-4-mini-instruct-GGUF",
    name: "Phi 4 Mini Instruct",
    author: "bartowski",
    publisher: "Microsoft",
    family: "Phi",
    architecture: "Phi 4",
    summary: "Small modern instruct model for lightweight productivity tasks and fast local responses.",
    tags: ["chat", "fast", "small"],
    capabilities: ["Chat", "Writing", "Reasoning"],
    useCases: ["Fast desktop assistant", "Low-latency Q&A", "Light drafting"],
    collections: ["Small and fast"],
    featuredCategory: "Small and fast",
    parameterLabel: "4B",
    parameterCountBillions: 4,
    contextWindowTokens: 16000,
    license: "MIT",
    homepage: "https://huggingface.co/bartowski/Phi-4-mini-instruct-GGUF",
    releaseDate: "2025-01-15",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Slightly better compact default if you want more quality than Phi 3.5 while staying lightweight.",
    strengths: ["Fast", "Low-memory friendly", "Better compact reasoning than older 3B-tier models"],
    limitations: ["Still not a substitute for strong 7B models"],
    benchmarkTokensPerSecond: 61,
    minimumRamGb: 6,
    recommendedRamGb: 10,
    minimumVramGb: 4,
    recommendedVramGb: 6
  }),
  curated({
    repoId: "bartowski/Qwen2.5-VL-7B-Instruct-GGUF",
    name: "Qwen2.5 VL 7B Instruct",
    author: "bartowski",
    publisher: "Qwen",
    family: "Qwen VL",
    architecture: "Qwen2.5-VL",
    summary: "Vision-capable local model for image-aware prompting, OCR-adjacent tasks, and multimodal inspection.",
    tags: ["vision", "multimodal", "reasoning"],
    capabilities: ["Vision", "Reasoning", "Chat"],
    modalities: ["Text", "Vision"],
    useCases: ["Image Q&A", "Visual inspection", "Mixed text-image workflows"],
    collections: ["Vision models", "Power users"],
    featuredCategory: "Vision models",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 32768,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Qwen2.5-VL-7B-Instruct-GGUF",
    releaseDate: "2025-02-06",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Choose this only if you specifically need local multimodal support.",
    strengths: ["Vision support", "Solid general-purpose reasoning"],
    limitations: ["Heavier runtime setup expectations", "Not needed for text-only users"],
    benchmarkTokensPerSecond: 21,
    minimumRamGb: 12,
    recommendedRamGb: 20,
    minimumVramGb: 8,
    recommendedVramGb: 12
  }),
  curated({
    repoId: "bartowski/Llama-3.2-11B-Vision-Instruct-GGUF",
    name: "Llama 3.2 11B Vision",
    author: "bartowski",
    publisher: "Meta",
    family: "Llama Vision",
    architecture: "Llama 3.2 Vision",
    summary: "Multimodal local model for users who want Meta-family vision capability on a stronger machine.",
    tags: ["vision", "multimodal", "chat"],
    capabilities: ["Vision", "Chat", "Reasoning"],
    modalities: ["Text", "Vision"],
    useCases: ["Image-aware assistance", "Visual Q&A", "Multimodal workflows"],
    collections: ["Vision models", "Power users"],
    featuredCategory: "Vision models",
    parameterLabel: "11B",
    parameterCountBillions: 11,
    contextWindowTokens: 128000,
    license: "Llama 3.2 Community",
    homepage: "https://huggingface.co/bartowski/Llama-3.2-11B-Vision-Instruct-GGUF",
    releaseDate: "2024-09-25",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Better fit if you specifically want a Meta-family multimodal model.",
    strengths: ["Vision support", "Familiar Llama ecosystem"],
    limitations: ["Heavy for casual users", "Text-only users should choose a smaller standard model"],
    benchmarkTokensPerSecond: 18,
    minimumRamGb: 14,
    recommendedRamGb: 24,
    minimumVramGb: 10,
    recommendedVramGb: 14
  }),
  curated({
    repoId: "bartowski/c4ai-command-r7b-12-2024-GGUF",
    name: "Command R7B",
    author: "bartowski",
    publisher: "Cohere",
    family: "Command",
    architecture: "Command R",
    summary: "Retrieval-friendly assistant model oriented toward grounded responses and knowledge work.",
    tags: ["chat", "rag", "reasoning"],
    capabilities: ["Chat", "Grounded Q&A", "Writing"],
    useCases: ["RAG workflows", "Document-grounded chat", "Knowledge tasks"],
    collections: ["General purpose", "Best for your machine"],
    featuredCategory: "General purpose",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 128000,
    license: "Cohere",
    homepage: "https://huggingface.co/bartowski/c4ai-command-r7b-12-2024-GGUF",
    releaseDate: "2024-12-10",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Good pick when grounded Q&A matters more than raw coding or raw benchmark chasing.",
    strengths: ["RAG-friendly behavior", "Strong enterprise-style assistant tone"],
    limitations: ["Less popular community ecosystem", "Not first choice for coding"],
    benchmarkTokensPerSecond: 35,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Aya-Expanse-8B-GGUF",
    name: "Aya Expanse 8B",
    author: "bartowski",
    publisher: "Cohere For AI",
    family: "Aya",
    architecture: "Aya Expanse",
    summary: "Multilingual assistant model that is especially useful when English is not the only language in your workflow.",
    tags: ["multilingual", "chat", "writing"],
    capabilities: ["Multilingual", "Chat", "Writing"],
    useCases: ["Spanish workflows", "Translation-adjacent tasks", "International drafting"],
    collections: ["Multilingual", "Best for your machine"],
    featuredCategory: "Multilingual",
    parameterLabel: "8B",
    parameterCountBillions: 8,
    contextWindowTokens: 8192,
    license: "CC-BY-NC",
    homepage: "https://huggingface.co/bartowski/Aya-Expanse-8B-GGUF",
    releaseDate: "2024-10-23",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Best when multilingual quality is more important than maximum coding or reasoning specialization.",
    strengths: ["Multilingual breadth", "Strong non-English utility"],
    limitations: ["Less ideal as a coding model", "Shorter context than leading long-context picks"],
    languages: ["English", "Spanish", "Portuguese", "French", "Arabic", "German"],
    benchmarkTokensPerSecond: 34,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Nous-Hermes-3-Llama-3.1-8B-GGUF",
    name: "Nous Hermes 3 Llama 3.1 8B",
    author: "bartowski",
    publisher: "Nous Research",
    family: "Nous Hermes",
    architecture: "Llama 3.1",
    summary: "Community-favored chat model with a more conversational tone and good everyday utility.",
    tags: ["chat", "writing", "general"],
    capabilities: ["Chat", "Writing", "Reasoning"],
    useCases: ["Everyday assistant", "Conversational drafting", "Flexible local chat"],
    collections: ["Best for most users", "General purpose"],
    featuredCategory: "Best for most users",
    parameterLabel: "8B",
    parameterCountBillions: 8,
    contextWindowTokens: 128000,
    license: "Llama 3.1 Community",
    homepage: "https://huggingface.co/bartowski/Nous-Hermes-3-Llama-3.1-8B-GGUF",
    releaseDate: "2024-08-01",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Good alternative if you want a more conversational community-tuned default than stock instruct variants.",
    strengths: ["Conversational feel", "Popular community tuning"],
    limitations: ["Less conservative than base instruct models", "Not the strongest coding or math choice"],
    benchmarkTokensPerSecond: 40,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/OpenThinker-7B-GGUF",
    name: "OpenThinker 7B",
    author: "bartowski",
    publisher: "OpenThinker",
    family: "OpenThinker",
    architecture: "Reasoning tuned",
    summary: "Another reasoning-biased 7B pick aimed at analysis-heavy workflows and chain-of-thought style prompting.",
    tags: ["reasoning", "analysis", "math"],
    capabilities: ["Reasoning", "Analysis", "Math"],
    useCases: ["Deliberate analysis", "Math-heavy prompts", "Research support"],
    collections: ["Reasoning picks"],
    featuredCategory: "Reasoning picks",
    parameterLabel: "7B",
    parameterCountBillions: 7,
    contextWindowTokens: 32768,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/OpenThinker-7B-GGUF",
    releaseDate: "2025-02-14",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Useful if you want another built-in reasoning-focused option beyond DeepSeek distills.",
    strengths: ["Reasoning bias", "Good analysis style"],
    limitations: ["Less broadly proven than mainstream families", "Not the fastest"],
    benchmarkGsm8k: 86.0,
    benchmarkTokensPerSecond: 28,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/EXAONE-3.5-7.8B-Instruct-GGUF",
    name: "EXAONE 3.5 7.8B Instruct",
    author: "bartowski",
    publisher: "LG AI Research",
    family: "EXAONE",
    architecture: "EXAONE 3.5",
    summary: "Alternative high-quality 7B-tier instruct model for users who want variety beyond Llama and Qwen defaults.",
    tags: ["chat", "reasoning", "writing"],
    capabilities: ["Chat", "Reasoning", "Writing"],
    useCases: ["Alternative daily driver", "Drafting", "General local chat"],
    collections: ["General purpose"],
    featuredCategory: "General purpose",
    parameterLabel: "7.8B",
    parameterCountBillions: 7.8,
    contextWindowTokens: 32768,
    license: "EXAONE AI Model License",
    homepage: "https://huggingface.co/bartowski/EXAONE-3.5-7.8B-Instruct-GGUF",
    releaseDate: "2024-12-07",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "A good alternate general-purpose pick if you want to compare families.",
    strengths: ["Solid instruct quality", "Useful alternative family"],
    limitations: ["Smaller community mindshare", "Less obvious default than Qwen or Llama"],
    benchmarkTokensPerSecond: 36,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  }),
  curated({
    repoId: "bartowski/Granite-3.1-8B-Instruct-GGUF",
    name: "Granite 3.1 8B Instruct",
    author: "bartowski",
    publisher: "IBM",
    family: "Granite",
    architecture: "Granite 3.1",
    summary: "Enterprise-oriented instruct model with a more grounded, utility-first feel for business and productivity tasks.",
    tags: ["chat", "enterprise", "writing"],
    capabilities: ["Chat", "Writing", "Summarization"],
    useCases: ["Business documents", "Summaries", "Operational assistant"],
    collections: ["General purpose"],
    featuredCategory: "General purpose",
    parameterLabel: "8B",
    parameterCountBillions: 8,
    contextWindowTokens: 128000,
    license: "Apache 2.0",
    homepage: "https://huggingface.co/bartowski/Granite-3.1-8B-Instruct-GGUF",
    releaseDate: "2024-11-20",
    recommendedQuantization: "Q4_K_M",
    recommendationReason: "Useful if you want a more restrained utility model instead of a personality-heavy chat model.",
    strengths: ["Grounded business tone", "Long context", "Good summarization"],
    limitations: ["Less enthusiast mindshare", "Not a leading coding pick"],
    benchmarkTokensPerSecond: 35,
    minimumRamGb: 8,
    recommendedRamGb: 16,
    minimumVramGb: 6,
    recommendedVramGb: 8
  })
];
